using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Globalization;

namespace FujiyBlog.Web.Areas.Admin.ViewModels
{
    public class AdminBasicSettings
    {
        [Required]
        [Display(Name = "Blog Name")]
        public string BlogName { get; set; }

        [Display(Name = "Blog Description")]
        public string BlogDescription { get; set; }

        [Required]
        public string Theme { get; set; }

        [Display(Name = "Posts Per Page")]
        public int PostsPerPage { get; set; }

        [Required]
        [Display(Name = "Time Zone")]
        public string TimeZoneId { get; set; }

        [Required]
        [Display(Name = "Language")]
        public string Language { get; set; }

        [Display(Name = "Application Insights Instrumentation Key")]
        public string ApplicationInsightsInstrumentationKey { get; set; }

        [Display(Name = "Custom Code"), DataType(DataType.MultilineText)]
        public string CustomCode { get; set; }

        public IEnumerable<SelectListItem> Themes { get; set; }

        public IEnumerable<SelectListItem> TimeZones { get; set; }

        private static List<SelectListItem> languagesCache;
        public List<SelectListItem> Languages
        {
            get
            {

                if (languagesCache == null)
                {
                    List<SelectListItem> languages = new List<SelectListItem> { new SelectListItem { Text = "Auto", Value = "Auto" }, new SelectListItem { Text = "English", Value = "en" }, new SelectListItem { Text = "Portuguese (Brazil)", Value = "pt-br" } };
                    //foreach (CultureInfo culture in CultureInfoCache.GetCultures())
                    //{
                    //    if (Resources.Labels.ResourceManager.GetString("Add", culture) != null)
                    //    {
                    //        languages.Add(new SelectListItem { Text = culture.DisplayName, Value = culture.Name });
                    //    }
                    //}
                    languagesCache = languages;
                }
                return languagesCache;
            }
        }
    }

    public static class CultureInfoCache
    {
        private static readonly ConcurrentDictionary<string, CacheEntry> _cache = new ConcurrentDictionary<string, CacheEntry>();

        public static IEnumerable<CultureInfo> GetCultures()
        {
            foreach (var cultureName in CultureInfoList.KnownCultureNames)
            {
                var culture = GetCultureInfo(cultureName);
                if (culture != null)
                {
                    yield return culture;
                }
            }
        }

        public static CultureInfo GetCultureInfo(string name)
        {
            // Allow only known culture names as this API is called with input from users (HTTP requests) and
            // creating CultureInfo objects is expensive and we don't want it to throw either.
            if (name == null || !CultureInfoList.KnownCultureNames.Contains(name))
            {
                return null;
            }

            var entry = _cache.GetOrAdd(name, n =>
            {
                try
                {
                    return new CacheEntry(CultureInfo.ReadOnly(new CultureInfo(n)));
                }
                catch (CultureNotFoundException)
                {
                    // This can still throw as the list of culture names we have is generated from latest .NET Framework
                    // on latest Windows and thus contains names that won't be supported on lower framework or OS versions.
                    // We can just cache the null result in these cases as it's ultimately bound by the list anyway.
                    return new CacheEntry(cultureInfo: null);
                }
            });

            return entry.CultureInfo;
        }

        private class CacheEntry
        {
            public CacheEntry(CultureInfo cultureInfo)
            {
                CultureInfo = cultureInfo;
            }

            public CultureInfo CultureInfo { get; }
        }
    }

    public static class CultureInfoList
    {
        // This list of known cultures was generated by CultureInfoGenerator using .NET Framework 4.6 RC or later on
        // Microsoft Windows NT 6.2.9200.0.
        // As new versions of .NET Framework and Windows are released, this list should be regenerated to ensure it
        // contains the latest culture names.
        public static readonly HashSet<string> KnownCultureNames = new HashSet<string>
        {
            "",
            "af",
            "af-ZA",
            "am",
            "am-ET",
            "ar",
            "ar-AE",
            "ar-BH",
            "ar-DZ",
            "ar-EG",
            "ar-IQ",
            "ar-JO",
            "ar-KW",
            "ar-LB",
            "ar-LY",
            "ar-MA",
            "ar-OM",
            "ar-QA",
            "ar-SA",
            "ar-SY",
            "ar-TN",
            "ar-YE",
            "arn",
            "arn-CL",
            "as",
            "as-IN",
            "az",
            "az-Cyrl",
            "az-Cyrl-AZ",
            "az-Latn",
            "az-Latn-AZ",
            "ba",
            "ba-RU",
            "be",
            "be-BY",
            "bg",
            "bg-BG",
            "bn",
            "bn-BD",
            "bn-IN",
            "bo",
            "bo-CN",
            "br",
            "br-FR",
            "bs",
            "bs-Cyrl",
            "bs-Cyrl-BA",
            "bs-Latn",
            "bs-Latn-BA",
            "ca",
            "ca-ES",
            "ca-ES-valencia",
            "chr",
            "chr-Cher",
            "chr-Cher-US",
            "co",
            "co-FR",
            "cs",
            "cs-CZ",
            "cy",
            "cy-GB",
            "da",
            "da-DK",
            "de",
            "de-AT",
            "de-CH",
            "de-DE",
            "de-LI",
            "de-LU",
            "dsb",
            "dsb-DE",
            "dv",
            "dv-MV",
            "el",
            "el-GR",
            "en",
            "en-029",
            "en-AU",
            "en-BZ",
            "en-CA",
            "en-GB",
            "en-HK",
            "en-IE",
            "en-IN",
            "en-JM",
            "en-MY",
            "en-NZ",
            "en-PH",
            "en-SG",
            "en-TT",
            "en-US",
            "en-ZA",
            "en-ZW",
            "es",
            "es-419",
            "es-AR",
            "es-BO",
            "es-CL",
            "es-CO",
            "es-CR",
            "es-DO",
            "es-EC",
            "es-ES",
            "es-GT",
            "es-HN",
            "es-MX",
            "es-NI",
            "es-PA",
            "es-PE",
            "es-PR",
            "es-PY",
            "es-SV",
            "es-US",
            "es-UY",
            "es-VE",
            "et",
            "et-EE",
            "eu",
            "eu-ES",
            "fa",
            "fa-IR",
            "ff",
            "ff-Latn",
            "ff-Latn-SN",
            "fi",
            "fi-FI",
            "fil",
            "fil-PH",
            "fo",
            "fo-FO",
            "fr",
            "fr-BE",
            "fr-CA",
            "fr-CD",
            "fr-CH",
            "fr-CI",
            "fr-CM",
            "fr-FR",
            "fr-HT",
            "fr-LU",
            "fr-MA",
            "fr-MC",
            "fr-ML",
            "fr-RE",
            "fr-SN",
            "fy",
            "fy-NL",
            "ga",
            "ga-IE",
            "gd",
            "gd-GB",
            "gl",
            "gl-ES",
            "gn",
            "gn-PY",
            "gsw",
            "gsw-FR",
            "gu",
            "gu-IN",
            "ha",
            "ha-Latn",
            "ha-Latn-NG",
            "haw",
            "haw-US",
            "he",
            "he-IL",
            "hi",
            "hi-IN",
            "hr",
            "hr-BA",
            "hr-HR",
            "hsb",
            "hsb-DE",
            "hu",
            "hu-HU",
            "hy",
            "hy-AM",
            "id",
            "id-ID",
            "ig",
            "ig-NG",
            "ii",
            "ii-CN",
            "is",
            "is-IS",
            "it",
            "it-CH",
            "it-IT",
            "iu",
            "iu-Cans",
            "iu-Cans-CA",
            "iu-Latn",
            "iu-Latn-CA",
            "ja",
            "ja-JP",
            "jv",
            "jv-Latn",
            "jv-Latn-ID",
            "ka",
            "ka-GE",
            "kk",
            "kk-KZ",
            "kl",
            "kl-GL",
            "km",
            "km-KH",
            "kn",
            "kn-IN",
            "ko",
            "ko-KR",
            "kok",
            "kok-IN",
            "ku",
            "ku-Arab",
            "ku-Arab-IQ",
            "ky",
            "ky-KG",
            "lb",
            "lb-LU",
            "lo",
            "lo-LA",
            "lt",
            "lt-LT",
            "lv",
            "lv-LV",
            "mg",
            "mg-MG",
            "mi",
            "mi-NZ",
            "mk",
            "mk-MK",
            "ml",
            "ml-IN",
            "mn",
            "mn-Cyrl",
            "mn-MN",
            "mn-Mong",
            "mn-Mong-CN",
            "mn-Mong-MN",
            "moh",
            "moh-CA",
            "mr",
            "mr-IN",
            "ms",
            "ms-BN",
            "ms-MY",
            "mt",
            "mt-MT",
            "my",
            "my-MM",
            "nb",
            "nb-NO",
            "ne",
            "ne-IN",
            "ne-NP",
            "nl",
            "nl-BE",
            "nl-NL",
            "nn",
            "nn-NO",
            "no",
            "nqo",
            "nqo-GN",
            "nso",
            "nso-ZA",
            "oc",
            "oc-FR",
            "om",
            "om-ET",
            "or",
            "or-IN",
            "pa",
            "pa-Arab",
            "pa-Arab-PK",
            "pa-IN",
            "pl",
            "pl-PL",
            "prs",
            "prs-AF",
            "ps",
            "ps-AF",
            "pt",
            "pt-AO",
            "pt-BR",
            "pt-PT",
            "qut",
            "qut-GT",
            "quz",
            "quz-BO",
            "quz-EC",
            "quz-PE",
            "rm",
            "rm-CH",
            "ro",
            "ro-MD",
            "ro-RO",
            "ru",
            "ru-RU",
            "rw",
            "rw-RW",
            "sa",
            "sa-IN",
            "sah",
            "sah-RU",
            "sd",
            "sd-Arab",
            "sd-Arab-PK",
            "se",
            "se-FI",
            "se-NO",
            "se-SE",
            "si",
            "si-LK",
            "sk",
            "sk-SK",
            "sl",
            "sl-SI",
            "sma",
            "sma-NO",
            "sma-SE",
            "smj",
            "smj-NO",
            "smj-SE",
            "smn",
            "smn-FI",
            "sms",
            "sms-FI",
            "sn",
            "sn-Latn",
            "sn-Latn-ZW",
            "so",
            "so-SO",
            "sq",
            "sq-AL",
            "sr",
            "sr-Cyrl",
            "sr-Cyrl-BA",
            "sr-Cyrl-CS",
            "sr-Cyrl-ME",
            "sr-Cyrl-RS",
            "sr-Latn",
            "sr-Latn-BA",
            "sr-Latn-CS",
            "sr-Latn-ME",
            "sr-Latn-RS",
            "st",
            "st-ZA",
            "sv",
            "sv-FI",
            "sv-SE",
            "sw",
            "sw-KE",
            "syr",
            "syr-SY",
            "ta",
            "ta-IN",
            "ta-LK",
            "te",
            "te-IN",
            "tg",
            "tg-Cyrl",
            "tg-Cyrl-TJ",
            "th",
            "th-TH",
            "ti",
            "ti-ER",
            "ti-ET",
            "tk",
            "tk-TM",
            "tn",
            "tn-BW",
            "tn-ZA",
            "tr",
            "tr-TR",
            "ts",
            "ts-ZA",
            "tt",
            "tt-RU",
            "tzm",
            "tzm-Latn",
            "tzm-Latn-DZ",
            "tzm-Tfng",
            "tzm-Tfng-MA",
            "ug",
            "ug-CN",
            "uk",
            "uk-UA",
            "ur",
            "ur-IN",
            "ur-PK",
            "uz",
            "uz-Cyrl",
            "uz-Cyrl-UZ",
            "uz-Latn",
            "uz-Latn-UZ",
            "vi",
            "vi-VN",
            "wo",
            "wo-SN",
            "xh",
            "xh-ZA",
            "yo",
            "yo-NG",
            "zgh",
            "zgh-Tfng",
            "zgh-Tfng-MA",
            "zh",
            "zh-CN",
            "zh-Hans",
            "zh-Hant",
            "zh-HK",
            "zh-MO",
            "zh-SG",
            "zh-TW",
            "zu",
            "zu-ZA",
            "zh-CHS",
            "zh-CHT"
        };
    }
}