// <auto-generated />
namespace FujiyBlog.Core.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PostRevision : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PostRevision));
        
        string IMigrationMetadata.Id
        {
            get { return "201208170219234_PostRevision"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
