// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace FujiyBlog.Web.Areas.Admin.Controllers
{
    public partial class SettingController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SettingController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LogView()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LogView);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LogDelete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LogDelete);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SettingController Actions { get { return MVC.Admin.Setting; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Setting";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Setting";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Email = "Email";
            public readonly string Comments = "Comments";
            public readonly string Import = "Import";
            public readonly string ImportPost = "Import";
            public readonly string ImportSuccessful = "ImportSuccessful";
            public readonly string SocialNetworks = "SocialNetworks";
            public readonly string Feed = "Feed";
            public readonly string Cache = "Cache";
            public readonly string ClearCache = "ClearCache";
            public readonly string Logs = "Logs";
            public readonly string LogView = "LogView";
            public readonly string LogDelete = "LogDelete";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Email = "Email";
            public const string Comments = "Comments";
            public const string Import = "Import";
            public const string ImportPost = "Import";
            public const string ImportSuccessful = "ImportSuccessful";
            public const string SocialNetworks = "SocialNetworks";
            public const string Feed = "Feed";
            public const string Cache = "Cache";
            public const string ClearCache = "ClearCache";
            public const string Logs = "Logs";
            public const string LogView = "LogView";
            public const string LogDelete = "LogDelete";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string settings = "settings";
        }
        static readonly ActionParamsClass_Email s_params_Email = new ActionParamsClass_Email();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Email EmailParams { get { return s_params_Email; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Email
        {
            public readonly string settings = "settings";
        }
        static readonly ActionParamsClass_Comments s_params_Comments = new ActionParamsClass_Comments();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Comments CommentsParams { get { return s_params_Comments; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Comments
        {
            public readonly string settings = "settings";
        }
        static readonly ActionParamsClass_SocialNetworks s_params_SocialNetworks = new ActionParamsClass_SocialNetworks();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SocialNetworks SocialNetworksParams { get { return s_params_SocialNetworks; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SocialNetworks
        {
            public readonly string settings = "settings";
        }
        static readonly ActionParamsClass_Feed s_params_Feed = new ActionParamsClass_Feed();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Feed FeedParams { get { return s_params_Feed; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Feed
        {
            public readonly string settings = "settings";
        }
        static readonly ActionParamsClass_LogView s_params_LogView = new ActionParamsClass_LogView();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LogView LogViewParams { get { return s_params_LogView; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LogView
        {
            public readonly string file = "file";
        }
        static readonly ActionParamsClass_LogDelete s_params_LogDelete = new ActionParamsClass_LogDelete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LogDelete LogDeleteParams { get { return s_params_LogDelete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LogDelete
        {
            public readonly string file = "file";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Layout = "_Layout";
                public readonly string Cache = "Cache";
                public readonly string Comments = "Comments";
                public readonly string Email = "Email";
                public readonly string Feed = "Feed";
                public readonly string Import = "Import";
                public readonly string ImportSuccessful = "ImportSuccessful";
                public readonly string Index = "Index";
                public readonly string Logs = "Logs";
                public readonly string SocialNetworks = "SocialNetworks";
            }
            public readonly string _Layout = "~/Areas/Admin/Views/Setting/_Layout.cshtml";
            public readonly string Cache = "~/Areas/Admin/Views/Setting/Cache.cshtml";
            public readonly string Comments = "~/Areas/Admin/Views/Setting/Comments.cshtml";
            public readonly string Email = "~/Areas/Admin/Views/Setting/Email.cshtml";
            public readonly string Feed = "~/Areas/Admin/Views/Setting/Feed.cshtml";
            public readonly string Import = "~/Areas/Admin/Views/Setting/Import.cshtml";
            public readonly string ImportSuccessful = "~/Areas/Admin/Views/Setting/ImportSuccessful.cshtml";
            public readonly string Index = "~/Areas/Admin/Views/Setting/Index.cshtml";
            public readonly string Logs = "~/Areas/Admin/Views/Setting/Logs.cshtml";
            public readonly string SocialNetworks = "~/Areas/Admin/Views/Setting/SocialNetworks.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_SettingController : FujiyBlog.Web.Areas.Admin.Controllers.SettingController
    {
        public T4MVC_SettingController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, FujiyBlog.Web.Areas.Admin.ViewModels.AdminBasicSettings settings);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(FujiyBlog.Web.Areas.Admin.ViewModels.AdminBasicSettings settings)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "settings", settings);
            IndexOverride(callInfo, settings);
            return callInfo;
        }

        [NonAction]
        partial void EmailOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Email()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Email);
            EmailOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void EmailOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, FujiyBlog.Web.Areas.Admin.ViewModels.AdminEmailSettings settings);

        [NonAction]
        public override System.Web.Mvc.ActionResult Email(FujiyBlog.Web.Areas.Admin.ViewModels.AdminEmailSettings settings)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Email);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "settings", settings);
            EmailOverride(callInfo, settings);
            return callInfo;
        }

        [NonAction]
        partial void CommentsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Comments()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Comments);
            CommentsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CommentsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, FujiyBlog.Web.Areas.Admin.ViewModels.AdminCommentsSettings settings);

        [NonAction]
        public override System.Web.Mvc.ActionResult Comments(FujiyBlog.Web.Areas.Admin.ViewModels.AdminCommentsSettings settings)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Comments);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "settings", settings);
            CommentsOverride(callInfo, settings);
            return callInfo;
        }

        [NonAction]
        partial void ImportOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Import()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Import);
            ImportOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ImportPostOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ImportPost()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ImportPost);
            ImportPostOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ImportSuccessfulOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ImportSuccessful()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ImportSuccessful);
            ImportSuccessfulOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SocialNetworksOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SocialNetworks()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SocialNetworks);
            SocialNetworksOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SocialNetworksOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, FujiyBlog.Web.Areas.Admin.ViewModels.AdminSettingsSocialNetworks settings);

        [NonAction]
        public override System.Web.Mvc.ActionResult SocialNetworks(FujiyBlog.Web.Areas.Admin.ViewModels.AdminSettingsSocialNetworks settings)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SocialNetworks);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "settings", settings);
            SocialNetworksOverride(callInfo, settings);
            return callInfo;
        }

        [NonAction]
        partial void FeedOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Feed()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Feed);
            FeedOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void FeedOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, FujiyBlog.Web.Areas.Admin.ViewModels.AdminFeedSettings settings);

        [NonAction]
        public override System.Web.Mvc.ActionResult Feed(FujiyBlog.Web.Areas.Admin.ViewModels.AdminFeedSettings settings)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Feed);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "settings", settings);
            FeedOverride(callInfo, settings);
            return callInfo;
        }

        [NonAction]
        partial void CacheOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Cache()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Cache);
            CacheOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ClearCacheOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ClearCache()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ClearCache);
            ClearCacheOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void LogsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Logs()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Logs);
            LogsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void LogViewOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string file);

        [NonAction]
        public override System.Web.Mvc.ActionResult LogView(string file)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LogView);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "file", file);
            LogViewOverride(callInfo, file);
            return callInfo;
        }

        [NonAction]
        partial void LogDeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string file);

        [NonAction]
        public override System.Web.Mvc.ActionResult LogDelete(string file)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LogDelete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "file", file);
            LogDeleteOverride(callInfo, file);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108
