//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets6082CA18EF3FDD517070FE4F636DABB4671524FEFD6A7D639F18980D2150A5AD))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// The type contains views for EntitySets and AssociationSets that were generated at design time.
    /// </Summary>
    public sealed class ViewsForBaseEntitySets6082CA18EF3FDD517070FE4F636DABB4671524FEFD6A7D639F18980D2150A5AD : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// The constructor stores the views for the extents and also the hash values generated based on the metadata and mapping closure and views.
        /// </Summary>
        public ViewsForBaseEntitySets6082CA18EF3FDD517070FE4F636DABB4671524FEFD6A7D639F18980D2150A5AD()
        {
            this.EdmEntityContainerName = "FujiyBlogDatabase";
            this.StoreEntityContainerName = "CodeFirstDatabase";
            this.HashOverMappingClosure = "7717eb831fb3894066da00a5b13b072490489c3d33faeb1867d00d7c303c2473";
            this.HashOverAllExtentViews = "a9c19cf772995aa0395234f3806b8ec595f3f0d003514a7993a7cb917bac41e2";
            this.ViewCount = 25;
        }
        
        /// <Summary>
        /// The method returns the view for the index given.
        /// </Summary>
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                return GetView0();
            }
            if ((index == 1))
            {
                return GetView1();
            }
            if ((index == 2))
            {
                return GetView2();
            }
            if ((index == 3))
            {
                return GetView3();
            }
            if ((index == 4))
            {
                return GetView4();
            }
            if ((index == 5))
            {
                return GetView5();
            }
            if ((index == 6))
            {
                return GetView6();
            }
            if ((index == 7))
            {
                return GetView7();
            }
            if ((index == 8))
            {
                return GetView8();
            }
            if ((index == 9))
            {
                return GetView9();
            }
            if ((index == 10))
            {
                return GetView10();
            }
            if ((index == 11))
            {
                return GetView11();
            }
            if ((index == 12))
            {
                return GetView12();
            }
            if ((index == 13))
            {
                return GetView13();
            }
            if ((index == 14))
            {
                return GetView14();
            }
            if ((index == 15))
            {
                return GetView15();
            }
            if ((index == 16))
            {
                return GetView16();
            }
            if ((index == 17))
            {
                return GetView17();
            }
            if ((index == 18))
            {
                return GetView18();
            }
            if ((index == 19))
            {
                return GetView19();
            }
            if ((index == 20))
            {
                return GetView20();
            }
            if ((index == 21))
            {
                return GetView21();
            }
            if ((index == 22))
            {
                return GetView22();
            }
            if ((index == 23))
            {
                return GetView23();
            }
            if ((index == 24))
            {
                return GetView24();
            }
            throw new System.IndexOutOfRangeException();
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.PostComment
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView0()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(3692);
            viewString.Append("\r\n    SELECT VALUE -- Constructing PostComment\r\n        [CodeFirstDatabaseSchema");
            viewString.Append(".PostComment](T7.PostComment_Id, T7.PostComment_AuthorName, T7.PostComment_Autho");
            viewString.Append("rEmail, T7.PostComment_AuthorWebsite, T7.PostComment_Comment, T7.PostComment_IpA");
            viewString.Append("ddress, T7.PostComment_Avatar, T7.PostComment_CreationDate, T7.PostComment_IsApp");
            viewString.Append("roved, T7.PostComment_IsDeleted, T7.[PostComment.Author_Id], T7.[PostComment.Mod");
            viewString.Append("eratedBy_Id], T7.[PostComment.Post_Id], T7.[PostComment.ParentComment_Id])\r\n    ");
            viewString.Append("FROM (\r\n        SELECT T3.PostComment_Id, T3.PostComment_AuthorName, T3.PostComm");
            viewString.Append("ent_AuthorEmail, T3.PostComment_AuthorWebsite, T3.PostComment_Comment, T3.PostCo");
            viewString.Append("mment_IpAddress, T3.PostComment_Avatar, T3.PostComment_CreationDate, T3.PostComm");
            viewString.Append("ent_IsApproved, T3.PostComment_IsDeleted, T4.[PostComment.Author_Id], T5.[PostCo");
            viewString.Append("mment.ModeratedBy_Id], T3.[PostComment.Post_Id], T6.[PostComment.ParentComment_I");
            viewString.Append("d], T3._from0, T3._from1, (T6._from2 AND T6._from2 IS NOT NULL) AS _from2, (T4._");
            viewString.Append("from3 AND T4._from3 IS NOT NULL) AS _from3, (T5._from4 AND T5._from4 IS NOT NULL");
            viewString.Append(") AS _from4\r\n        FROM  (\r\n            SELECT T1.PostComment_Id, T1.PostComme");
            viewString.Append("nt_AuthorName, T1.PostComment_AuthorEmail, T1.PostComment_AuthorWebsite, T1.Post");
            viewString.Append("Comment_Comment, T1.PostComment_IpAddress, T1.PostComment_Avatar, T1.PostComment");
            viewString.Append("_CreationDate, T1.PostComment_IsApproved, T1.PostComment_IsDeleted, T2.[PostComm");
            viewString.Append("ent.Post_Id], T1._from0, T2._from1\r\n            FROM  (\r\n                SELECT ");
            viewString.Append("\r\n                    T.Id AS PostComment_Id, \r\n                    T.AuthorName");
            viewString.Append(" AS PostComment_AuthorName, \r\n                    T.AuthorEmail AS PostComment_A");
            viewString.Append("uthorEmail, \r\n                    T.AuthorWebsite AS PostComment_AuthorWebsite, ");
            viewString.Append("\r\n                    T.Comment AS PostComment_Comment, \r\n                    T.");
            viewString.Append("IpAddress AS PostComment_IpAddress, \r\n                    T.Avatar AS PostCommen");
            viewString.Append("t_Avatar, \r\n                    T.CreationDate AS PostComment_CreationDate, \r\n  ");
            viewString.Append("                  T.IsApproved AS PostComment_IsApproved, \r\n                    ");
            viewString.Append("T.IsDeleted AS PostComment_IsDeleted, \r\n                    True AS _from0\r\n    ");
            viewString.Append("            FROM FujiyBlogDatabase.PostComments AS T) AS T1\r\n                INN");
            viewString.Append("ER JOIN (\r\n                SELECT \r\n                    Key(T.PostComment_Post_S");
            viewString.Append("ource).Id AS PostComment_Id, \r\n                    Key(T.PostComment_Post_Target");
            viewString.Append(").Id AS [PostComment.Post_Id], \r\n                    True AS _from1\r\n           ");
            viewString.Append("     FROM FujiyBlogDatabase.PostComment_Post AS T) AS T2\r\n                ON T1.");
            viewString.Append("PostComment_Id = T2.PostComment_Id) AS T3\r\n            LEFT OUTER JOIN (\r\n      ");
            viewString.Append("      SELECT \r\n                Key(T.User_AuthoredPostComments_Target).Id AS Pos");
            viewString.Append("tComment_Id, \r\n                Key(T.User_AuthoredPostComments_Source).Id AS [Po");
            viewString.Append("stComment.Author_Id], \r\n                True AS _from3\r\n            FROM FujiyBl");
            viewString.Append("ogDatabase.User_AuthoredPostComments AS T) AS T4\r\n            ON T3.PostComment_");
            viewString.Append("Id = T4.PostComment_Id\r\n            LEFT OUTER JOIN (\r\n            SELECT \r\n    ");
            viewString.Append("            Key(T.User_ModeratedPostComments_Target).Id AS PostComment_Id, \r\n   ");
            viewString.Append("             Key(T.User_ModeratedPostComments_Source).Id AS [PostComment.Moderat");
            viewString.Append("edBy_Id], \r\n                True AS _from4\r\n            FROM FujiyBlogDatabase.U");
            viewString.Append("ser_ModeratedPostComments AS T) AS T5\r\n            ON T3.PostComment_Id = T5.Pos");
            viewString.Append("tComment_Id\r\n            LEFT OUTER JOIN (\r\n            SELECT \r\n               ");
            viewString.Append(" Key(T.PostComment_ParentComment_Source).Id AS PostComment_Id, \r\n               ");
            viewString.Append(" Key(T.PostComment_ParentComment_Target).Id AS [PostComment.ParentComment_Id], \r");
            viewString.Append("\n                True AS _from2\r\n            FROM FujiyBlogDatabase.PostComment_");
            viewString.Append("ParentComment AS T) AS T6\r\n            ON T3.PostComment_Id = T6.PostComment_Id\r");
            viewString.Append("\n    ) AS T7");
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.PostComment", viewString.ToString());
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.Post
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView1()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.Post", "\r\n    SELECT VALUE -- Constructing Post\r\n        [CodeFirstDatabaseSchema.Post](T" +
                    "3.Post_Id, T3.Post_Title, T3.Post_Description, T3.Post_Slug, T3.Post_Content, T3" +
                    ".Post_CreationDate, T3.Post_LastModificationDate, T3.Post_PublicationDate, T3.Po" +
                    "st_IsPublished, T3.Post_IsCommentEnabled, T3.Post_IsDeleted, T3.[Post.Author_Id]" +
                    ")\r\n    FROM (\r\n        SELECT T1.Post_Id, T2.Post_Title, T2.Post_Description, T2" +
                    ".Post_Slug, T2.Post_Content, T2.Post_CreationDate, T2.Post_LastModificationDate," +
                    " T2.Post_PublicationDate, T2.Post_IsPublished, T2.Post_IsCommentEnabled, T2.Post" +
                    "_IsDeleted, T1.[Post.Author_Id], T2._from0, T1._from1\r\n        FROM  (\r\n        " +
                    "    SELECT \r\n                Key(T.Post_Author_Source).Id AS Post_Id, \r\n        " +
                    "        Key(T.Post_Author_Target).Id AS [Post.Author_Id], \r\n                True" +
                    " AS _from1\r\n            FROM FujiyBlogDatabase.Post_Author AS T) AS T1\r\n        " +
                    "    INNER JOIN (\r\n            SELECT \r\n                T.Id AS Post_Id, \r\n      " +
                    "          T.Title AS Post_Title, \r\n                T.Description AS Post_Descrip" +
                    "tion, \r\n                T.Slug AS Post_Slug, \r\n                T.Content AS Post" +
                    "_Content, \r\n                T.CreationDate AS Post_CreationDate, \r\n             " +
                    "   T.LastModificationDate AS Post_LastModificationDate, \r\n                T.Publ" +
                    "icationDate AS Post_PublicationDate, \r\n                T.IsPublished AS Post_IsP" +
                    "ublished, \r\n                T.IsCommentEnabled AS Post_IsCommentEnabled, \r\n     " +
                    "           T.IsDeleted AS Post_IsDeleted, \r\n                True AS _from0\r\n    " +
                    "        FROM FujiyBlogDatabase.Posts AS T) AS T2\r\n            ON T1.Post_Id = T2" +
                    ".Post_Id\r\n    ) AS T3");
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.User
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView2()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.User", @"
    SELECT VALUE -- Constructing User
        [CodeFirstDatabaseSchema.User](T1.User_Id, T1.User_Username, T1.User_Email, T1.User_Password, T1.User_DisplayName, T1.User_FullName, T1.User_Location, T1.User_CreationDate, T1.User_LastLoginDate, T1.User_About, T1.User_BirthDate)
    FROM (
        SELECT 
            T.Id AS User_Id, 
            T.Username AS User_Username, 
            T.Email AS User_Email, 
            T.Password AS User_Password, 
            T.DisplayName AS User_DisplayName, 
            T.FullName AS User_FullName, 
            T.Location AS User_Location, 
            T.CreationDate AS User_CreationDate, 
            T.LastLoginDate AS User_LastLoginDate, 
            T.About AS User_About, 
            T.BirthDate AS User_BirthDate, 
            True AS _from0
        FROM FujiyBlogDatabase.Users AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.Tag
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView3()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.Tag", @"
    SELECT VALUE -- Constructing Tag
        [CodeFirstDatabaseSchema.Tag](T1.Tag_Id, T1.Tag_Name)
    FROM (
        SELECT 
            T.Id AS Tag_Id, 
            T.Name AS Tag_Name, 
            True AS _from0
        FROM FujiyBlogDatabase.Tags AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.Category
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView4()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.Category", @"
    SELECT VALUE -- Constructing Category
        [CodeFirstDatabaseSchema.Category](T1.Category_Id, T1.Category_Name)
    FROM (
        SELECT 
            T.Id AS Category_Id, 
            T.Name AS Category_Name, 
            True AS _from0
        FROM FujiyBlogDatabase.Categories AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.TagPost
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView5()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.TagPost", @"
    SELECT VALUE -- Constructing TagPost
        [CodeFirstDatabaseSchema.TagPost](T1.[TagPost.Tag_Id], T1.[TagPost.Post_Id])
    FROM (
        SELECT 
            Key(T.Tag_Posts_Source).Id AS [TagPost.Tag_Id], 
            Key(T.Tag_Posts_Target).Id AS [TagPost.Post_Id], 
            True AS _from0
        FROM FujiyBlogDatabase.Tag_Posts AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.CategoryPost
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView6()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.CategoryPost", @"
    SELECT VALUE -- Constructing CategoryPost
        [CodeFirstDatabaseSchema.CategoryPost](T1.[CategoryPost.Category_Id], T1.[CategoryPost.Post_Id])
    FROM (
        SELECT 
            Key(T.Category_Posts_Source).Id AS [CategoryPost.Category_Id], 
            Key(T.Category_Posts_Target).Id AS [CategoryPost.Post_Id], 
            True AS _from0
        FROM FujiyBlogDatabase.Category_Posts AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for FujiyBlogDatabase.PostComments
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView7()
        {
            System.Text.StringBuilder viewString = new System.Text.StringBuilder(2482);
            viewString.Append("\r\n    SELECT VALUE -- Constructing PostComments\r\n        [FujiyBlog.EntityFramew");
            viewString.Append("ork.PostComment](T1.PostComment_Id, T1.PostComment_AuthorName, T1.PostComment_Au");
            viewString.Append("thorEmail, T1.PostComment_AuthorWebsite, T1.PostComment_Comment, T1.PostComment_");
            viewString.Append("IpAddress, T1.PostComment_Avatar, T1.PostComment_CreationDate, T1.PostComment_Is");
            viewString.Append("Approved, T1.PostComment_IsDeleted) WITH \r\n        RELATIONSHIP(CREATEREF(FujiyB");
            viewString.Append("logDatabase.Users, ROW(T1.[User_AuthoredPostComments.User_AuthoredPostComments_S");
            viewString.Append("ource.Id]),[FujiyBlog.EntityFramework.User]),[FujiyBlog.EntityFramework.User_Aut");
            viewString.Append("horedPostComments],User_AuthoredPostComments_Target,User_AuthoredPostComments_So");
            viewString.Append("urce) \r\n        RELATIONSHIP(CREATEREF(FujiyBlogDatabase.Users, ROW(T1.[User_Mod");
            viewString.Append("eratedPostComments.User_ModeratedPostComments_Source.Id]),[FujiyBlog.EntityFrame");
            viewString.Append("work.User]),[FujiyBlog.EntityFramework.User_ModeratedPostComments],User_Moderate");
            viewString.Append("dPostComments_Target,User_ModeratedPostComments_Source) \r\n        RELATIONSHIP(C");
            viewString.Append("REATEREF(FujiyBlogDatabase.Posts, ROW(T1.[PostComment_Post.PostComment_Post_Targ");
            viewString.Append("et.Id]),[FujiyBlog.EntityFramework.Post]),[FujiyBlog.EntityFramework.PostComment");
            viewString.Append("_Post],PostComment_Post_Source,PostComment_Post_Target) \r\n        RELATIONSHIP(C");
            viewString.Append("REATEREF(FujiyBlogDatabase.PostComments, ROW(T1.[PostComment_ParentComment.PostC");
            viewString.Append("omment_ParentComment_Target.Id]),[FujiyBlog.EntityFramework.PostComment]),[Fujiy");
            viewString.Append("Blog.EntityFramework.PostComment_ParentComment],PostComment_ParentComment_Source");
            viewString.Append(",PostComment_ParentComment_Target) \r\n    FROM (\r\n        SELECT \r\n            T.");
            viewString.Append("Id AS PostComment_Id, \r\n            T.AuthorName AS PostComment_AuthorName, \r\n  ");
            viewString.Append("          T.AuthorEmail AS PostComment_AuthorEmail, \r\n            T.AuthorWebsit");
            viewString.Append("e AS PostComment_AuthorWebsite, \r\n            T.Comment AS PostComment_Comment, ");
            viewString.Append("\r\n            T.IpAddress AS PostComment_IpAddress, \r\n            T.Avatar AS Po");
            viewString.Append("stComment_Avatar, \r\n            T.CreationDate AS PostComment_CreationDate, \r\n  ");
            viewString.Append("          T.IsApproved AS PostComment_IsApproved, \r\n            T.IsDeleted AS P");
            viewString.Append("ostComment_IsDeleted, \r\n            True AS _from0, \r\n            T.Author_Id AS");
            viewString.Append(" [User_AuthoredPostComments.User_AuthoredPostComments_Source.Id], \r\n            ");
            viewString.Append("T.ModeratedBy_Id AS [User_ModeratedPostComments.User_ModeratedPostComments_Sourc");
            viewString.Append("e.Id], \r\n            T.Post_Id AS [PostComment_Post.PostComment_Post_Target.Id],");
            viewString.Append(" \r\n            T.ParentComment_Id AS [PostComment_ParentComment.PostComment_Pare");
            viewString.Append("ntComment_Target.Id]\r\n        FROM CodeFirstDatabase.PostComment AS T\r\n    ) AS ");
            viewString.Append("T1");
            return new System.Collections.Generic.KeyValuePair<string, string>("FujiyBlogDatabase.PostComments", viewString.ToString());
        }
        
        /// <Summary>
        /// return view for FujiyBlogDatabase.Posts
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView8()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FujiyBlogDatabase.Posts", @"
    SELECT VALUE -- Constructing Posts
        [FujiyBlog.EntityFramework.Post](T1.Post_Id, T1.Post_Title, T1.Post_Description, T1.Post_Slug, T1.Post_Content, T1.Post_CreationDate, T1.Post_LastModificationDate, T1.Post_PublicationDate, T1.Post_IsPublished, T1.Post_IsCommentEnabled, T1.Post_IsDeleted) WITH 
        RELATIONSHIP(CREATEREF(FujiyBlogDatabase.Users, ROW(T1.[Post_Author.Post_Author_Target.Id]),[FujiyBlog.EntityFramework.User]),[FujiyBlog.EntityFramework.Post_Author],Post_Author_Source,Post_Author_Target) 
    FROM (
        SELECT 
            T.Id AS Post_Id, 
            T.Title AS Post_Title, 
            T.Description AS Post_Description, 
            T.Slug AS Post_Slug, 
            T.Content AS Post_Content, 
            T.CreationDate AS Post_CreationDate, 
            T.LastModificationDate AS Post_LastModificationDate, 
            T.PublicationDate AS Post_PublicationDate, 
            T.IsPublished AS Post_IsPublished, 
            T.IsCommentEnabled AS Post_IsCommentEnabled, 
            T.IsDeleted AS Post_IsDeleted, 
            True AS _from0, 
            T.Author_Id AS [Post_Author.Post_Author_Target.Id]
        FROM CodeFirstDatabase.Post AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for FujiyBlogDatabase.Users
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView9()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FujiyBlogDatabase.Users", @"
    SELECT VALUE -- Constructing Users
        [FujiyBlog.EntityFramework.User](T1.User_Id, T1.User_Username, T1.User_Email, T1.User_Password, T1.User_DisplayName, T1.User_FullName, T1.User_Location, T1.User_CreationDate, T1.User_LastLoginDate, T1.User_About, T1.User_BirthDate)
    FROM (
        SELECT 
            T.Id AS User_Id, 
            T.Username AS User_Username, 
            T.Email AS User_Email, 
            T.Password AS User_Password, 
            T.DisplayName AS User_DisplayName, 
            T.FullName AS User_FullName, 
            T.Location AS User_Location, 
            T.CreationDate AS User_CreationDate, 
            T.LastLoginDate AS User_LastLoginDate, 
            T.About AS User_About, 
            T.BirthDate AS User_BirthDate, 
            True AS _from0
        FROM CodeFirstDatabase.User AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for FujiyBlogDatabase.Tags
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView10()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FujiyBlogDatabase.Tags", @"
    SELECT VALUE -- Constructing Tags
        [FujiyBlog.EntityFramework.Tag](T1.Tag_Id, T1.Tag_Name)
    FROM (
        SELECT 
            T.Id AS Tag_Id, 
            T.Name AS Tag_Name, 
            True AS _from0
        FROM CodeFirstDatabase.Tag AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for FujiyBlogDatabase.Categories
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView11()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FujiyBlogDatabase.Categories", @"
    SELECT VALUE -- Constructing Categories
        [FujiyBlog.EntityFramework.Category](T1.Category_Id, T1.Category_Name)
    FROM (
        SELECT 
            T.Id AS Category_Id, 
            T.Name AS Category_Name, 
            True AS _from0
        FROM CodeFirstDatabase.Category AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for FujiyBlogDatabase.User_AuthoredPostComments
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView12()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FujiyBlogDatabase.User_AuthoredPostComments", @"
    SELECT VALUE -- Constructing User_AuthoredPostComments
        [FujiyBlog.EntityFramework.User_AuthoredPostComments](T3.[User_AuthoredPostComments.User_AuthoredPostComments_Source], T3.[User_AuthoredPostComments.User_AuthoredPostComments_Target])
    FROM (
        SELECT -- Constructing User_AuthoredPostComments_Source
            CreateRef(FujiyBlogDatabase.Users, row(T2.[User_AuthoredPostComments.User_AuthoredPostComments_Source.Id]),[FujiyBlog.EntityFramework.User]) AS [User_AuthoredPostComments.User_AuthoredPostComments_Source], 
            T2.[User_AuthoredPostComments.User_AuthoredPostComments_Target]
        FROM (
            SELECT -- Constructing User_AuthoredPostComments_Target
                CreateRef(FujiyBlogDatabase.PostComments, row(T1.[User_AuthoredPostComments.User_AuthoredPostComments_Target.Id]),[FujiyBlog.EntityFramework.PostComment]) AS [User_AuthoredPostComments.User_AuthoredPostComments_Target], 
                T1.[User_AuthoredPostComments.User_AuthoredPostComments_Source.Id]
            FROM (
                SELECT 
                    T.Author_Id AS [User_AuthoredPostComments.User_AuthoredPostComments_Source.Id], 
                    T.Id AS [User_AuthoredPostComments.User_AuthoredPostComments_Target.Id], 
                    True AS _from0
                FROM CodeFirstDatabase.PostComment AS T
                WHERE T.Author_Id IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// return view for FujiyBlogDatabase.User_ModeratedPostComments
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView13()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FujiyBlogDatabase.User_ModeratedPostComments", "\r\n    SELECT VALUE -- Constructing User_ModeratedPostComments\r\n        [FujiyBlog" +
                    ".EntityFramework.User_ModeratedPostComments](T3.[User_ModeratedPostComments.User" +
                    "_ModeratedPostComments_Source], T3.[User_ModeratedPostComments.User_ModeratedPos" +
                    "tComments_Target])\r\n    FROM (\r\n        SELECT -- Constructing User_ModeratedPos" +
                    "tComments_Source\r\n            CreateRef(FujiyBlogDatabase.Users, row(T2.[User_Mo" +
                    "deratedPostComments.User_ModeratedPostComments_Source.Id]),[FujiyBlog.EntityFram" +
                    "ework.User]) AS [User_ModeratedPostComments.User_ModeratedPostComments_Source], " +
                    "\r\n            T2.[User_ModeratedPostComments.User_ModeratedPostComments_Target]\r" +
                    "\n        FROM (\r\n            SELECT -- Constructing User_ModeratedPostComments_T" +
                    "arget\r\n                CreateRef(FujiyBlogDatabase.PostComments, row(T1.[User_Mo" +
                    "deratedPostComments.User_ModeratedPostComments_Target.Id]),[FujiyBlog.EntityFram" +
                    "ework.PostComment]) AS [User_ModeratedPostComments.User_ModeratedPostComments_Ta" +
                    "rget], \r\n                T1.[User_ModeratedPostComments.User_ModeratedPostCommen" +
                    "ts_Source.Id]\r\n            FROM (\r\n                SELECT \r\n                    " +
                    "T.ModeratedBy_Id AS [User_ModeratedPostComments.User_ModeratedPostComments_Sourc" +
                    "e.Id], \r\n                    T.Id AS [User_ModeratedPostComments.User_ModeratedP" +
                    "ostComments_Target.Id], \r\n                    True AS _from0\r\n                FR" +
                    "OM CodeFirstDatabase.PostComment AS T\r\n                WHERE T.ModeratedBy_Id IS" +
                    " NOT NULL\r\n            ) AS T1\r\n        ) AS T2\r\n    ) AS T3");
        }
        
        /// <Summary>
        /// return view for FujiyBlogDatabase.Post_Author
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView14()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FujiyBlogDatabase.Post_Author", @"
    SELECT VALUE -- Constructing Post_Author
        [FujiyBlog.EntityFramework.Post_Author](T3.[Post_Author.Post_Author_Source], T3.[Post_Author.Post_Author_Target])
    FROM (
        SELECT -- Constructing Post_Author_Source
            CreateRef(FujiyBlogDatabase.Posts, row(T2.[Post_Author.Post_Author_Source.Id]),[FujiyBlog.EntityFramework.Post]) AS [Post_Author.Post_Author_Source], 
            T2.[Post_Author.Post_Author_Target]
        FROM (
            SELECT -- Constructing Post_Author_Target
                CreateRef(FujiyBlogDatabase.Users, row(T1.[Post_Author.Post_Author_Target.Id]),[FujiyBlog.EntityFramework.User]) AS [Post_Author.Post_Author_Target], 
                T1.[Post_Author.Post_Author_Source.Id]
            FROM (
                SELECT 
                    T.Id AS [Post_Author.Post_Author_Source.Id], 
                    T.Author_Id AS [Post_Author.Post_Author_Target.Id], 
                    True AS _from0
                FROM CodeFirstDatabase.Post AS T
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// return view for FujiyBlogDatabase.Tag_Posts
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView15()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FujiyBlogDatabase.Tag_Posts", @"
    SELECT VALUE -- Constructing Tag_Posts
        [FujiyBlog.EntityFramework.Tag_Posts](T3.[Tag_Posts.Tag_Posts_Source], T3.[Tag_Posts.Tag_Posts_Target])
    FROM (
        SELECT -- Constructing Tag_Posts_Source
            CreateRef(FujiyBlogDatabase.Tags, row(T2.[Tag_Posts.Tag_Posts_Source.Id]),[FujiyBlog.EntityFramework.Tag]) AS [Tag_Posts.Tag_Posts_Source], 
            T2.[Tag_Posts.Tag_Posts_Target]
        FROM (
            SELECT -- Constructing Tag_Posts_Target
                CreateRef(FujiyBlogDatabase.Posts, row(T1.[Tag_Posts.Tag_Posts_Target.Id]),[FujiyBlog.EntityFramework.Post]) AS [Tag_Posts.Tag_Posts_Target], 
                T1.[Tag_Posts.Tag_Posts_Source.Id]
            FROM (
                SELECT 
                    T.Tag_Id AS [Tag_Posts.Tag_Posts_Source.Id], 
                    T.Post_Id AS [Tag_Posts.Tag_Posts_Target.Id], 
                    True AS _from0
                FROM CodeFirstDatabase.TagPost AS T
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// return view for FujiyBlogDatabase.Category_Posts
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView16()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FujiyBlogDatabase.Category_Posts", @"
    SELECT VALUE -- Constructing Category_Posts
        [FujiyBlog.EntityFramework.Category_Posts](T3.[Category_Posts.Category_Posts_Source], T3.[Category_Posts.Category_Posts_Target])
    FROM (
        SELECT -- Constructing Category_Posts_Source
            CreateRef(FujiyBlogDatabase.Categories, row(T2.[Category_Posts.Category_Posts_Source.Id]),[FujiyBlog.EntityFramework.Category]) AS [Category_Posts.Category_Posts_Source], 
            T2.[Category_Posts.Category_Posts_Target]
        FROM (
            SELECT -- Constructing Category_Posts_Target
                CreateRef(FujiyBlogDatabase.Posts, row(T1.[Category_Posts.Category_Posts_Target.Id]),[FujiyBlog.EntityFramework.Post]) AS [Category_Posts.Category_Posts_Target], 
                T1.[Category_Posts.Category_Posts_Source.Id]
            FROM (
                SELECT 
                    T.Category_Id AS [Category_Posts.Category_Posts_Source.Id], 
                    T.Post_Id AS [Category_Posts.Category_Posts_Target.Id], 
                    True AS _from0
                FROM CodeFirstDatabase.CategoryPost AS T
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// return view for FujiyBlogDatabase.PostComment_Post
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView17()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FujiyBlogDatabase.PostComment_Post", @"
    SELECT VALUE -- Constructing PostComment_Post
        [FujiyBlog.EntityFramework.PostComment_Post](T3.[PostComment_Post.PostComment_Post_Source], T3.[PostComment_Post.PostComment_Post_Target])
    FROM (
        SELECT -- Constructing PostComment_Post_Source
            CreateRef(FujiyBlogDatabase.PostComments, row(T2.[PostComment_Post.PostComment_Post_Source.Id]),[FujiyBlog.EntityFramework.PostComment]) AS [PostComment_Post.PostComment_Post_Source], 
            T2.[PostComment_Post.PostComment_Post_Target]
        FROM (
            SELECT -- Constructing PostComment_Post_Target
                CreateRef(FujiyBlogDatabase.Posts, row(T1.[PostComment_Post.PostComment_Post_Target.Id]),[FujiyBlog.EntityFramework.Post]) AS [PostComment_Post.PostComment_Post_Target], 
                T1.[PostComment_Post.PostComment_Post_Source.Id]
            FROM (
                SELECT 
                    T.Id AS [PostComment_Post.PostComment_Post_Source.Id], 
                    T.Post_Id AS [PostComment_Post.PostComment_Post_Target.Id], 
                    True AS _from0
                FROM CodeFirstDatabase.PostComment AS T
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// return view for FujiyBlogDatabase.PostComment_ParentComment
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView18()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FujiyBlogDatabase.PostComment_ParentComment", @"
    SELECT VALUE -- Constructing PostComment_ParentComment
        [FujiyBlog.EntityFramework.PostComment_ParentComment](T3.[PostComment_ParentComment.PostComment_ParentComment_Source], T3.[PostComment_ParentComment.PostComment_ParentComment_Target])
    FROM (
        SELECT -- Constructing PostComment_ParentComment_Source
            CreateRef(FujiyBlogDatabase.PostComments, row(T2.[PostComment_ParentComment.PostComment_ParentComment_Source.Id]),[FujiyBlog.EntityFramework.PostComment]) AS [PostComment_ParentComment.PostComment_ParentComment_Source], 
            T2.[PostComment_ParentComment.PostComment_ParentComment_Target]
        FROM (
            SELECT -- Constructing PostComment_ParentComment_Target
                CreateRef(FujiyBlogDatabase.PostComments, row(T1.[PostComment_ParentComment.PostComment_ParentComment_Target.Id]),[FujiyBlog.EntityFramework.PostComment]) AS [PostComment_ParentComment.PostComment_ParentComment_Target], 
                T1.[PostComment_ParentComment.PostComment_ParentComment_Source.Id]
            FROM (
                SELECT 
                    T.Id AS [PostComment_ParentComment.PostComment_ParentComment_Source.Id], 
                    T.ParentComment_Id AS [PostComment_ParentComment.PostComment_ParentComment_Target.Id], 
                    True AS _from0
                FROM CodeFirstDatabase.PostComment AS T
                WHERE T.ParentComment_Id IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.Setting
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView19()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.Setting", @"
    SELECT VALUE -- Constructing Setting
        [CodeFirstDatabaseSchema.Setting](T1.Setting_Id, T1.Setting_Description, T1.Setting_Value)
    FROM (
        SELECT 
            T.Id AS Setting_Id, 
            T.Description AS Setting_Description, 
            T.[Value] AS Setting_Value, 
            True AS _from0
        FROM FujiyBlogDatabase.Settings AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for FujiyBlogDatabase.Settings
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView20()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FujiyBlogDatabase.Settings", @"
    SELECT VALUE -- Constructing Settings
        [FujiyBlog.EntityFramework.Setting](T1.Setting_Id, T1.Setting_Description, T1.Setting_Value)
    FROM (
        SELECT 
            T.Id AS Setting_Id, 
            T.Description AS Setting_Description, 
            T.[Value] AS Setting_Value, 
            True AS _from0
        FROM CodeFirstDatabase.Setting AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.WidgetSetting
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView21()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.WidgetSetting", @"
    SELECT VALUE -- Constructing WidgetSetting
        [CodeFirstDatabaseSchema.WidgetSetting](T1.WidgetSetting_Id, T1.WidgetSetting_Name, T1.WidgetSetting_WidgetZone, T1.WidgetSetting_Position, T1.WidgetSetting_Settings)
    FROM (
        SELECT 
            T.Id AS WidgetSetting_Id, 
            T.Name AS WidgetSetting_Name, 
            T.WidgetZone AS WidgetSetting_WidgetZone, 
            T.Position AS WidgetSetting_Position, 
            T.Settings AS WidgetSetting_Settings, 
            True AS _from0
        FROM FujiyBlogDatabase.WidgetSettings AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for FujiyBlogDatabase.WidgetSettings
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView22()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FujiyBlogDatabase.WidgetSettings", @"
    SELECT VALUE -- Constructing WidgetSettings
        [FujiyBlog.EntityFramework.WidgetSetting](T1.WidgetSetting_Id, T1.WidgetSetting_Name, T1.WidgetSetting_WidgetZone, T1.WidgetSetting_Position, T1.WidgetSetting_Settings)
    FROM (
        SELECT 
            T.Id AS WidgetSetting_Id, 
            T.Name AS WidgetSetting_Name, 
            T.WidgetZone AS WidgetSetting_WidgetZone, 
            T.Position AS WidgetSetting_Position, 
            T.Settings AS WidgetSetting_Settings, 
            True AS _from0
        FROM CodeFirstDatabase.WidgetSetting AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for CodeFirstDatabase.EdmMetadata
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView23()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("CodeFirstDatabase.EdmMetadata", @"
    SELECT VALUE -- Constructing EdmMetadata
        [CodeFirstDatabaseSchema.EdmMetadata](T1.EdmMetadata_Id, T1.EdmMetadata_ModelHash)
    FROM (
        SELECT 
            T.Id AS EdmMetadata_Id, 
            T.ModelHash AS EdmMetadata_ModelHash, 
            True AS _from0
        FROM FujiyBlogDatabase.EdmMetadatas AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for FujiyBlogDatabase.EdmMetadatas
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView24()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("FujiyBlogDatabase.EdmMetadatas", @"
    SELECT VALUE -- Constructing EdmMetadatas
        [FujiyBlog.EntityFramework.EdmMetadata](T1.EdmMetadata_Id, T1.EdmMetadata_ModelHash)
    FROM (
        SELECT 
            T.Id AS EdmMetadata_Id, 
            T.ModelHash AS EdmMetadata_ModelHash, 
            True AS _from0
        FROM CodeFirstDatabase.EdmMetadata AS T
    ) AS T1");
        }
    }
}
